name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master
  repository_dispatch:
    types: [deploy]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install PNPM
        uses: pnpm/action-setup@v3

      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          cache: "pnpm"

      - name: Install tooling
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          cache: true

      - name: Install step
        run: "pnpm install"

      - name: Build step
        run: "pnpm astro:build"

      - name: Upload to Deno Deploy
        run: "DENO_DEPLOY_TOKEN=${{ secrets.DENO_DEPLOY_TOKEN }} pnpm run deploy"
